### ISSUE TITLE
Each "layer" of a "block" in residual learning model is actually a block.

### ISSUE THREAD

**Issue by skylarbpayne** [pkmital/tensorflow_tutorials#5]
for each block, for each layer, make 3 conv layers. These three conv layers constitute the concept of a block in the original paper. But you're repeating identical blocks.

So instead of there being 4 blocks, there are actually 12 in your example.

It seems your intention was to have 12 total layers, split into 4 blocks, but instead it seems you have 36 layers in 12 blocks.

This may be what you intended -- But the paper used 34 layers in most of it's experiments, so 36 is quite a jump ;).

Here's a tensorboard graph of one of the "blocks" so you can see what I'm referring to.
![screen shot 2016-02-10 at 9 59 52 pm](https://cloud.githubusercontent.com/assets/4830598/12970302/ce49f986-d041-11e5-8c2a-06388b4c4cc0.png)

**Comment by pkmital** [comment]
I'm not sure!  I was trying to replicate the 50 layer architecture, with 3x repeats instead of 3, 4, 6, 3 repeats of each block.  So the inner loop is how many times to repeat each block.  And the outer loop defines the properties of each block.  Does it still seem incorrect?

**Comment by pkmital** [comment]
But it should probably be named a block instead of a layer as you suggest.  The outer loop could be named block_type or something to that effect...

**Comment by skylarbpayne** [comment]
Well each "block" you have has three "layers" + an upscale and each "layer" has 3 convolutional layers.

So each block has 3 \* 3 + 1 = 10 layers. With 4 blocks, you have 40 layers. Add in the conv, max pool, and conv that starts before the blocks: 43 layers. Lastly, add in the average pool and linear layer at the end: 45 layers total is what I count.

Based on what you said, you're doing exactly that. Maybe a more helpful name like "BlockRepeater" or at least a comment to make the distinction would help :).

**Comment by pkmital** [comment]
Yes that's right.  The naming is incorrect.  The process seems correct to me.  The inner loop should be called, e.g. residual_block, rather than layer as you say.  And the outer one could then be called blocks.  This is based off the 50 layer model, though with half the size of filters, and only 3x of each inner residual block instead of [3x, 4x, 6x, 3x].

<img width="1081" alt="screen shot 2016-02-12 at 8 24 57 am" src="https://cloud.githubusercontent.com/assets/429252/13022527/06cf6894-d197-11e5-8f2f-33d48c225961.png">

**Comment by pkmital** [comment]
Changed `layer_i` and `num_layers` to `repeat_i` and `num_repeats`.
